# Generated by Django 4.1.2 on 2022-10-16 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0001_initial"),
    ]

    operations = [
        
    ]
