# Generated by Django 4.1.2 on 2022-10-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0002_remove_flight_co2_emission"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="co2_emission",
            field=models.IntegerField(null=True),
        ),
    ]
