# Generated by Django 4.1.2 on 2022-10-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0003_flight_co2_emission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="co2_emission",
            field=models.FloatField(null=True),
        ),
    ]
