# Generated by Django 4.1.2 on 2022-10-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0004_alter_flight_co2_emission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="co2_emission",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
