# Generated by Django 4.1.2 on 2022-10-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flight", "0005_alter_flight_co2_emission"),
    ]

    operations = [
        migrations.RemoveField(model_name="flight", name="co2_emission",),
    ]
